apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-api-mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-api-mysql-pod
  template:
    metadata:
      labels:
        app: author-api-mysql-pod
    spec:
      containers:
        - name: author-api-mysql-container
          image: mysql:8.0
          ports:
            - name: author-mysql-cp
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: thisIsReallyStrongPassword123
            - name: MYSQL_DATABASE
              value: prod
            - name: MYSQL_USER
              value: mysql
            - name: MYSQL_PASSWORD
              value: thisIsReallyStrongPassword123
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: author-api-mysql-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: author-api-mysql-pod
  ports:
    - name: author-mysql-cip
      protocol: TCP
      port: 3306
      targetPort: author-mysql-cp

---
apiVersion: v1
kind: Service
metadata:
  name: author-api-mysql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: author-api-mysql-pod
  ports:
    - name: author-mysql-lp
      protocol: TCP
      port: 3306
      targetPort: author-mysql-cp
